"""subtitle_translation_jobs

Revision ID: 00386555715c
Revises: ca2fe11c13e4
Create Date: 2026-05-14 13:42:32.547255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00386555715c'
down_revision: Union[str, Sequence[str], None] = 'ca2fe11c13e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subtitle_translation_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_subtitle_url', sa.String(length=2048), nullable=False),
    sa.Column('target_lang', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('result_subtitle_url', sa.String(length=2048), nullable=True),
    sa.Column('segments_count', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.String(length=2048), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subtitle_translation_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subtitle_translation_jobs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_subtitle_translation_jobs_target_lang'), ['target_lang'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subtitle_translation_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subtitle_translation_jobs_target_lang'))
        batch_op.drop_index(batch_op.f('ix_subtitle_translation_jobs_status'))

    op.drop_table('subtitle_translation_jobs')
    # ### end Alembic commands ###
