"""initial_schema_contents_explanations_words

Revision ID: 029c19229b91
Revises: 
Create Date: 2026-05-14 11:26:22.165707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '029c19229b91'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contents',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('author', sa.String(length=256), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('cefr_level', sa.String(length=8), nullable=False),
    sa.Column('play_mode', sa.String(length=16), nullable=False),
    sa.Column('video_url', sa.String(length=1024), nullable=True),
    sa.Column('youtube_id', sa.String(length=32), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=1024), nullable=False),
    sa.Column('subtitle_url', sa.String(length=1024), nullable=True),
    sa.Column('vocabulary_url', sa.String(length=1024), nullable=True),
    sa.Column('explanation_url', sa.String(length=1024), nullable=True),
    sa.Column('categories', sa.JSON(), nullable=False),
    sa.Column('category_color_hex', sa.Integer(), nullable=False),
    sa.Column('is_recommended', sa.Boolean(), nullable=False),
    sa.Column('classify_confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contents_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_contents_updated_at'), ['updated_at'], unique=False)

    op.create_table('words',
    sa.Column('word', sa.String(length=64), nullable=False),
    sa.Column('phonetic', sa.String(length=128), nullable=False),
    sa.Column('level', sa.String(length=8), nullable=False),
    sa.Column('definitions', sa.JSON(), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('hit_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('word')
    )
    op.create_table('explanations',
    sa.Column('video_id', sa.String(length=64), nullable=False),
    sa.Column('segment_id', sa.Integer(), nullable=False),
    sa.Column('sentence', sa.String(length=2048), nullable=False),
    sa.Column('natural_translation', sa.String(length=2048), nullable=False),
    sa.Column('core_explanation', sa.String(length=2048), nullable=False),
    sa.Column('key_vocab', sa.JSON(), nullable=False),
    sa.Column('grammar_point', sa.String(length=2048), nullable=True),
    sa.Column('cultural_note', sa.String(length=2048), nullable=True),
    sa.Column('pronunciation_tip', sa.String(length=2048), nullable=True),
    sa.Column('similar_expressions', sa.JSON(), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['contents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('video_id', 'segment_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('explanations')
    op.drop_table('words')
    with op.batch_alter_table('contents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contents_updated_at'))
        batch_op.drop_index(batch_op.f('ix_contents_status'))

    op.drop_table('contents')
    # ### end Alembic commands ###
