"""feedback_jobs_users_quota_pronunciation_chat

Revision ID: ca2fe11c13e4
Revises: a2f1c8d4e3b7
Create Date: 2026-05-14 11:31:10.908086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca2fe11c13e4'
down_revision: Union[str, Sequence[str], None] = '029c19229b91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # subtitle_jobs：之前的中间 migration 被合并到这里，避免迁移历史断裂
    op.create_table('subtitle_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=False),
    sa.Column('youtube_id', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('result_subtitle_url', sa.String(length=2048), nullable=True),
    sa.Column('segments_count', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.String(length=2048), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subtitle_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subtitle_jobs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_subtitle_jobs_youtube_id'), ['youtube_id'], unique=False)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=True),
    sa.Column('scenario', sa.String(length=32), nullable=False),
    sa.Column('messages', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_sessions_scenario'), ['scenario'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('pronunciation_scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=True),
    sa.Column('video_id', sa.String(length=64), nullable=False),
    sa.Column('segment_id', sa.Integer(), nullable=False),
    sa.Column('target_text', sa.String(length=2048), nullable=False),
    sa.Column('spoken_text', sa.String(length=2048), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pronunciation_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pronunciation_scores_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pronunciation_scores_video_id'), ['video_id'], unique=False)

    op.create_table('quota_usage',
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('day', sa.String(length=10), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'day', 'kind')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('display_name', sa.String(length=128), nullable=True),
    sa.Column('tier', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_tier'), ['tier'], unique=False)

    op.create_table('content_feedback',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('video_id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('note', sa.String(length=1024), nullable=True),
    sa.Column('client_fp', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['contents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('content_feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_content_feedback_client_fp'), ['client_fp'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_feedback_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_feedback_video_id'), ['video_id'], unique=False)

    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('tier', sa.String(length=16), nullable=False),
    sa.Column('apple_transaction_id', sa.String(length=64), nullable=False),
    sa.Column('apple_original_id', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscriptions_apple_original_id'), ['apple_original_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_apple_transaction_id'), ['apple_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscriptions_user_id'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_is_active'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_expires_at'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_apple_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_apple_original_id'))

    op.drop_table('subscriptions')
    with op.batch_alter_table('content_feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_feedback_video_id'))
        batch_op.drop_index(batch_op.f('ix_content_feedback_kind'))
        batch_op.drop_index(batch_op.f('ix_content_feedback_client_fp'))

    op.drop_table('content_feedback')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_tier'))

    op.drop_table('users')
    op.drop_table('quota_usage')
    with op.batch_alter_table('pronunciation_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pronunciation_scores_video_id'))
        batch_op.drop_index(batch_op.f('ix_pronunciation_scores_user_id'))

    op.drop_table('pronunciation_scores')
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_chat_sessions_scenario'))

    op.drop_table('chat_sessions')
    with op.batch_alter_table('subtitle_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subtitle_jobs_youtube_id'))
        batch_op.drop_index(batch_op.f('ix_subtitle_jobs_status'))

    op.drop_table('subtitle_jobs')
    # ### end Alembic commands ###
